name = "AutomotiveSafeRL"
uuid = "b9f89980-1857-11ea-0e00-456d252cee43"
repo = "https://github.com/MaximeBouton/AutomotiveSafeRL"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
AutoViz = "82aa6e0c-a491-5edf-8d4b-c16b98e4ea17"
AutomotiveDrivingModels = "99497e54-f3d6-53d3-a3a9-fa9315a7f1ba"
AutomotivePOMDPs = "dca8afc0-c686-11e8-0934-712707da73aa"
AutomotiveSensors = "9ec66b5e-c605-11e8-1454-ede748df6f96"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
BeliefUpdaters = "8bb6e9a1-7d73-552c-a44a-e5dc5634aac4"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DeepQLearning = "de0a67f4-c691-11e8-0034-5fc6e16e22d3"
DiscreteValueIteration = "4b033969-44f6-5439-a48b-c11fa3648068"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GridInterpolations = "bb4c363b-b914-514b-8517-4eb369bc008a"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LocalApproximationValueIteration = "a40420fb-f401-52da-a663-f502e5b95060"
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPPolicies = "182e52fb-cfd0-5e46-8c26-fd0667c990f4"
POMDPSimulators = "e0d0a172-29c6-5d4e-96d0-f262df5d01fd"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PedCar = "90cf7f26-d5c7-593d-a0e1-4a8367407571"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RLInterface = "3065fe53-3878-5aed-aae7-ab641be43734"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reel = "71555da5-176e-5e73-a222-aebc6c6e4f2f"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
